### ISSUE TITLE
add PL meetup?

### ISSUE THREAD

**Issue by jbenet** [memser-spaceport/labweek24-events#46]
may want to add https://www.eventbrite.com/e/pl-meetup-in-san-francisco-apr-2024-tickets-877622862607

cc @pandeyanujk

**Comment by pandeyanujk** [comment]
Thanks @jbenet. It's added now ([PR is here](https://github.com/memser-spaceport/labweek24-events/pull/48) for tracking).

**Comment by pandeyanujk** [comment]
[Added](https://github.com/memser-spaceport/labweek24-events/pull/48) to schedule.
